import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { getOpenRouterService } from '../ai/openRouterService';

/**
 * Chrome DevTools Test Generator - Creates comprehensive browser automation tests using Chrome DevTools Protocol
 */
export interface ChromeDevToolsTestSuite {
    name: string;
    description: string;
    tests: ChromeDevToolsTest[];
    config?: any;
}

export interface ChromeDevToolsTest {
    name: string;
    description: string;
    code: string;
    fileName: string;
}

export class ChromeDevToolsTestGenerator {
    private outputChannel: vscode.OutputChannel;

    constructor() {
        this.outputChannel = vscode.window.createOutputChannel('TestFox Chrome DevTools Generator');
    }

    /**
     * Create complete Chrome DevTools test folder structure with AI-generated tests
     */
    async generateChromeDevToolsSuite(projectPath: string, projectInfo: any): Promise<string> {
        this.outputChannel.appendLine('🔧 Starting Chrome DevTools test suite generation...');

        const devtoolsDir = path.join(projectPath, 'tests', 'chrome-devtools');
        
        // Create directory structure
        this.createDirectoryStructure(devtoolsDir);
        
        // Generate configuration
        await this.generateConfig(devtoolsDir, projectInfo);
        
        // Generate AI-powered tests
        await this.generateAITests(devtoolsDir, projectInfo);
        
        // Generate utility files
        await this.generateUtilities(devtoolsDir);
        
        this.outputChannel.appendLine(`✅ Chrome DevTools test suite created at: ${devtoolsDir}`);
        
        return devtoolsDir;
    }

    /**
     * Create directory structure
     */
    private createDirectoryStructure(baseDir: string): void {
        const dirs = [
            baseDir,
            path.join(baseDir, 'e2e'),
            path.join(baseDir, 'e2e', 'performance'),
            path.join(baseDir, 'e2e', 'network'),
            path.join(baseDir, 'e2e', 'console'),
            path.join(baseDir, 'e2e', 'security'),
            path.join(baseDir, 'utils'),
            path.join(baseDir, 'reports')
        ];

        for (const dir of dirs) {
            if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir, { recursive: true });
                this.outputChannel.appendLine(`📁 Created: ${dir}`);
            }
        }
    }

    /**
     * Generate Chrome DevTools configuration
     */
    private async generateConfig(devtoolsDir: string, projectInfo: any): Promise<void> {
        const baseUrl = projectInfo?.baseUrl || 'http://localhost:3000';
        
        const config = `{
  "name": "chrome-devtools-tests",
  "version": "1.0.0",
  "description": "Chrome DevTools Protocol tests generated by TestFox",
  "scripts": {
    "test": "node --experimental-vm-modules node_modules/.bin/jest",
    "test:performance": "node e2e/performance/performance.spec.js",
    "test:network": "node e2e/network/network.spec.js",
    "test:console": "node e2e/console/console.spec.js",
    "test:security": "node e2e/security/security.spec.js"
  },
  "dependencies": {
    "puppeteer": "^21.0.0",
    "chrome-launcher": "^1.1.0"
  },
  "devDependencies": {
    "jest": "^29.0.0"
  },
  "jest": {
    "testEnvironment": "node",
    "testMatch": ["**/*.spec.js"]
  }
}`;

        const configPath = path.join(devtoolsDir, 'package.json');
        fs.writeFileSync(configPath, config);
        this.outputChannel.appendLine(`📝 Generated: package.json`);

        // Generate jest.config.js
        const jestConfig = `/** @type {import('jest').Config} */
module.exports = {
  testEnvironment: 'node',
  testTimeout: 30000,
  reporters: [
    'default',
    ['jest-html-reporter', {
      outputPath: './reports/test-report.html',
      pageTitle: 'Chrome DevTools Test Report'
    }]
  ],
  collectCoverage: true,
  coverageDirectory: './reports/coverage'
};`;
        fs.writeFileSync(path.join(devtoolsDir, 'jest.config.js'), jestConfig);
        this.outputChannel.appendLine(`📝 Generated: jest.config.js`);
    }

    /**
     * Generate AI-powered tests
     */
    private async generateAITests(devtoolsDir: string, projectInfo: any): Promise<void> {
        const openRouter = getOpenRouterService();
        
        if (!openRouter.isConfigured()) {
            this.outputChannel.appendLine('⚠️ OpenRouter not configured, using template tests');
            await this.generateTemplateTests(devtoolsDir, projectInfo);
            return;
        }

        try {
            // Generate performance tests
            this.outputChannel.appendLine('🤖 Generating performance tests with AI...');
            const perfTestCode = await openRouter.generateTestCode(
                'Create Chrome DevTools Protocol performance tests: measure page load times, analyze resource loading, check Core Web Vitals (LCP, FID, CLS), monitor memory usage',
                'chrome-devtools'
            );
            fs.writeFileSync(
                path.join(devtoolsDir, 'e2e', 'performance', 'performance.spec.js'),
                this.cleanGeneratedCode(perfTestCode)
            );

            // Generate network tests
            this.outputChannel.appendLine('🤖 Generating network tests with AI...');
            const networkTestCode = await openRouter.generateTestCode(
                'Create Chrome DevTools Protocol network tests: monitor HTTP requests, check response times, validate API calls, analyze network waterfall',
                'chrome-devtools'
            );
            fs.writeFileSync(
                path.join(devtoolsDir, 'e2e', 'network', 'network.spec.js'),
                this.cleanGeneratedCode(networkTestCode)
            );

            // Generate console tests
            this.outputChannel.appendLine('🤖 Generating console tests with AI...');
            const consoleTestCode = await openRouter.generateTestCode(
                'Create Chrome DevTools Protocol console tests: capture console logs, detect errors and warnings, monitor console API usage',
                'chrome-devtools'
            );
            fs.writeFileSync(
                path.join(devtoolsDir, 'e2e', 'console', 'console.spec.js'),
                this.cleanGeneratedCode(consoleTestCode)
            );

            // Generate security tests
            this.outputChannel.appendLine('🤖 Generating security tests with AI...');
            const securityTestCode = await openRouter.generateTestCode(
                'Create Chrome DevTools Protocol security tests: check HTTPS usage, analyze security headers, detect mixed content, validate CSP policies',
                'chrome-devtools'
            );
            fs.writeFileSync(
                path.join(devtoolsDir, 'e2e', 'security', 'security.spec.js'),
                this.cleanGeneratedCode(securityTestCode)
            );

        } catch (error: any) {
            this.outputChannel.appendLine(`❌ AI generation failed: ${error.message}`);
            await this.generateTemplateTests(devtoolsDir, projectInfo);
        }
    }

    /**
     * Generate template tests when AI is not available
     */
    private async generateTemplateTests(devtoolsDir: string, projectInfo: any): Promise<void> {
        const baseUrl = projectInfo?.baseUrl || 'http://localhost:3000';

        // Performance tests
        const perfTests = `const puppeteer = require('puppeteer');

/**
 * Chrome DevTools Performance Tests - Generated by TestFox
 * Uses Chrome DevTools Protocol for deep browser analysis
 */

describe('Performance Tests', () => {
    let browser;
    let page;

    beforeAll(async () => {
        browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
        page = await browser.newPage();
    });

    afterAll(async () => {
        await browser.close();
    });

    test('page load time is under 3 seconds', async () => {
        const startTime = Date.now();
        await page.goto('${baseUrl}');
        await page.waitForLoadState('networkidle');
        const loadTime = Date.now() - startTime;
        
        expect(loadTime).toBeLessThan(3000);
    });

    test('Core Web Vitals - LCP is under 2.5s', async () => {
        await page.goto('${baseUrl}');
        
        const lcp = await page.evaluate(() => {
            return new Promise((resolve) => {
                new PerformanceObserver((list) => {
                    const entries = list.getEntries();
                    const lcpEntry = entries[entries.length - 1];
                    resolve(lcpEntry.startTime);
                }).observe({ entryTypes: ['largest-contentful-paint'] });
            });
        });
        
        expect(lcp).toBeLessThan(2500);
    });

    test('no memory leaks on navigation', async () => {
        await page.goto('${baseUrl}');
        
        const client = await page.target().createCDPSession();
        await client.send('HeapProfiler.enable');
        
        const heapBefore = await client.send('HeapProfiler.getHeapObjectId');
        
        // Navigate multiple times
        for (let i = 0; i < 5; i++) {
            await page.reload();
            await page.waitForTimeout(100);
        }
        
        const heapAfter = await client.send('HeapProfiler.getHeapObjectId');
        
        // Memory should not grow significantly
        expect(heapAfter).toBeDefined();
    });

    test('resource loading is optimized', async () => {
        const resources = [];
        
        page.on('response', async (response) => {
            const timing = response.timing();
            resources.push({
                url: response.url(),
                status: response.status(),
                timing
            });
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(2000);
        
        // Check for slow resources (>1s)
        const slowResources = resources.filter(r => {
            const duration = r.timing?.responseEnd - r.timing?.requestStart;
            return duration > 1000;
        });
        
        expect(slowResources.length).toBeLessThan(resources.length * 0.1); // Less than 10% slow
    });
});
`;
        fs.writeFileSync(path.join(devtoolsDir, 'e2e', 'performance', 'performance.spec.js'), perfTests);

        // Network tests
        const networkTests = `const puppeteer = require('puppeteer');

/**
 * Chrome DevTools Network Tests - Generated by TestFox
 */

describe('Network Tests', () => {
    let browser;
    let page;

    beforeAll(async () => {
        browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
        page = await browser.newPage();
    });

    afterAll(async () => {
        await browser.close();
    });

    test('all API calls return 200 status', async () => {
        const apiCalls = [];
        
        page.on('response', (response) => {
            if (response.url().includes('/api/')) {
                apiCalls.push({
                    url: response.url(),
                    status: response.status()
                });
            }
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(3000);
        
        for (const call of apiCalls) {
            expect(call.status).toBeGreaterThanOrEqual(200);
            expect(call.status).toBeLessThan(300);
        }
    });

    test('no failed network requests', async () => {
        const failedRequests = [];
        
        page.on('requestfailed', (request) => {
            failedRequests.push({
                url: request.url(),
                error: request.failure()?.errorText
            });
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(3000);
        
        expect(failedRequests).toHaveLength(0);
    });

    test('response times are under 500ms for API calls', async () => {
        const responseTimes = [];
        
        page.on('response', async (response) => {
            if (response.url().includes('/api/')) {
                const timing = response.timing();
                const duration = timing?.responseEnd - timing?.requestStart;
                responseTimes.push({ url: response.url(), duration });
            }
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(3000);
        
        for (const rt of responseTimes) {
            expect(rt.duration).toBeLessThan(500);
        }
    });
});
`;
        fs.writeFileSync(path.join(devtoolsDir, 'e2e', 'network', 'network.spec.js'), networkTests);

        // Console tests
        const consoleTests = `const puppeteer = require('puppeteer');

/**
 * Chrome DevTools Console Tests - Generated by TestFox
 */

describe('Console Tests', () => {
    let browser;
    let page;

    beforeAll(async () => {
        browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
        page = await browser.newPage();
    });

    afterAll(async () => {
        await browser.close();
    });

    test('no console errors on page load', async () => {
        const consoleErrors = [];
        
        page.on('console', (msg) => {
            if (msg.type() === 'error') {
                consoleErrors.push(msg.text());
            }
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(3000);
        
        expect(consoleErrors).toHaveLength(0);
    });

    test('no unhandled promise rejections', async () => {
        const unhandledRejections = [];
        
        page.on('pageerror', (error) => {
            unhandledRejections.push(error.message);
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(3000);
        
        expect(unhandledRejections).toHaveLength(0);
    });

    test('console warnings are minimal', async () => {
        const consoleWarnings = [];
        
        page.on('console', (msg) => {
            if (msg.type() === 'warning') {
                consoleWarnings.push(msg.text());
            }
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(3000);
        
        // Allow up to 5 warnings
        expect(consoleWarnings.length).toBeLessThanOrEqual(5);
    });
});
`;
        fs.writeFileSync(path.join(devtoolsDir, 'e2e', 'console', 'console.spec.js'), consoleTests);

        // Security tests
        const securityTests = `const puppeteer = require('puppeteer');

/**
 * Chrome DevTools Security Tests - Generated by TestFox
 */

describe('Security Tests', () => {
    let browser;
    let page;

    beforeAll(async () => {
        browser = await puppeteer.launch({
            headless: 'new',
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });
        page = await browser.newPage();
    });

    afterAll(async () => {
        await browser.close();
    });

    test('HTTPS is enforced', async () => {
        await page.goto('${baseUrl}');
        const securityDetails = await page.evaluate(() => {
            return window.isSecureContext;
        });
        
        // In production, should be secure context
        if (!'${baseUrl}'.includes('localhost')) {
            expect(securityDetails).toBe(true);
        }
    });

    test('no mixed content warnings', async () => {
        const mixedContent = [];
        
        const client = await page.target().createCDPSession();
        await client.send('Security.enable');
        
        client.on('Security.securityStateChanged', (event) => {
            if (event.securityState === 'insecure') {
                mixedContent.push(event);
            }
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(3000);
        
        expect(mixedContent).toHaveLength(0);
    });

    test('security headers are present', async () => {
        const headers = [];
        
        page.on('response', (response) => {
            if (response.url() === '${baseUrl}/') {
                headers.push(response.headers());
            }
        });
        
        await page.goto('${baseUrl}');
        await page.waitForTimeout(1000);
        
        if (headers.length > 0) {
            const securityHeaders = headers[0];
            
            // Check for recommended security headers
            expect(securityHeaders['x-content-type-options'] || securityHeaders['X-Content-Type-Options']).toBeTruthy();
        }
    });
});
`;
        fs.writeFileSync(path.join(devtoolsDir, 'e2e', 'security', 'security.spec.js'), securityTests);
    }

    /**
     * Generate utility files
     */
    private async generateUtilities(devtoolsDir: string): Promise<void> {
        // DevTools helper
        const devtoolsHelper = `const puppeteer = require('puppeteer');

/**
 * Chrome DevTools Helpers - Generated by TestFox
 */

class DevToolsHelper {
    constructor(page) {
        this.page = page;
        this.client = null;
    }

    async enable() {
        this.client = await this.page.target().createCDPSession();
        await this.client.send('Network.enable');
        await this.client.send('Performance.enable');
        await this.client.send('Console.enable');
        await this.client.send('Security.enable');
    }

    async getPerformanceMetrics() {
        const metrics = await this.client.send('Performance.getMetrics');
        return metrics.metrics;
    }

    async getNetworkLog() {
        const entries = [];
        this.client.on('Network.requestWillBeSent', (params) => {
            entries.push({
                type: 'request',
                url: params.request.url,
                method: params.request.method,
                timestamp: params.timestamp
            });
        });
        
        this.client.on('Network.responseReceived', (params) => {
            entries.push({
                type: 'response',
                url: params.response.url,
                status: params.response.status,
                timestamp: params.timestamp
            });
        });
        
        return entries;
    }

    async captureConsoleLogs() {
        const logs = [];
        this.client.on('Console.messageAdded', (params) => {
            logs.push(params.message);
        });
        return logs;
    }

    async takeHeapSnapshot() {
        await this.client.send('HeapProfiler.enable');
        const snapshot = await this.client.send('HeapProfiler.takeHeapSnapshot');
        return snapshot;
    }
}

module.exports = { DevToolsHelper };
`;
        fs.writeFileSync(path.join(devtoolsDir, 'utils', 'devtools-helper.js'), devtoolsHelper);

        // Test runner
        const testRunner = `/**
 * Chrome DevTools Test Runner - Generated by TestFox
 */

const { execSync } = require('child_process');
const path = require('path');

class ChromeDevToolsTestRunner {
    constructor(projectPath) {
        this.projectPath = projectPath;
        this.devtoolsDir = path.join(projectPath, 'tests', 'chrome-devtools');
    }

    async runTests() {
        try {
            const result = execSync('npm test', {
                cwd: this.devtoolsDir,
                encoding: 'utf8',
                timeout: 120000
            });
            
            return {
                success: true,
                output: result,
                reportPath: path.join(this.devtoolsDir, 'reports', 'test-report.html')
            };
        } catch (error) {
            return {
                success: false,
                output: error.stdout || error.message,
                error: error.message
            };
        }
    }

    async runSpecificTest(testType) {
        const testScripts = {
            performance: 'npm run test:performance',
            network: 'npm run test:network',
            console: 'npm run test:console',
            security: 'npm run test:security'
        };

        const script = testScripts[testType];
        if (!script) {
            throw new Error(\`Unknown test type: \${testType}\`);
        }

        try {
            const result = execSync(script, {
                cwd: this.devtoolsDir,
                encoding: 'utf8',
                timeout: 60000
            });
            
            return {
                success: true,
                output: result
            };
        } catch (error) {
            return {
                success: false,
                output: error.stdout || error.message
            };
        }
    }
}

module.exports = { ChromeDevToolsTestRunner };
`;
        fs.writeFileSync(path.join(devtoolsDir, 'utils', 'test-runner.js'), testRunner);

        // README
        const readme = `# Chrome DevTools Test Suite - Generated by TestFox

This comprehensive test suite uses Chrome DevTools Protocol for deep browser analysis.

## Structure

\`\`\`
tests/chrome-devtools/
├── package.json              # Dependencies
├── jest.config.js            # Test configuration
├── e2e/
│   ├── performance/          # Performance & Core Web Vitals
│   │   └── performance.spec.js
│   ├── network/              # Network monitoring
│   │   └── network.spec.js
│   ├── console/              # Console logs & errors
│   │   └── console.spec.js
│   └── security/             # Security headers & HTTPS
│       └── security.spec.js
├── utils/
│   ├── devtools-helper.js    # CDP helpers
│   └── test-runner.js        # Test execution
└── reports/                  # Test reports
\`\`\`

## Running Tests

\`\`\`bash
# Install dependencies
cd tests/chrome-devtools
npm install

# Run all tests
npm test

# Run specific test suites
npm run test:performance
npm run test:network
npm run test:console
npm run test:security
\`\`\`

## What These Tests Cover

- **Performance**: Page load times, Core Web Vitals (LCP, FID, CLS), memory usage
- **Network**: HTTP request monitoring, response times, failed requests
- **Console**: Error detection, warning tracking, unhandled rejections
- **Security**: HTTPS validation, security headers, mixed content detection

## MCP Server Configuration

\`\`\`json
{
  "mcpServers": {
    "chrome-devtools": {
      "command": "npx",
      "args": [
        "@modelcontextprotocol/server-chrome",
        "--headless"
      ]
    }
  }
}
\`\`\`

## Generated by
TestFox AI 🤖
`;
        fs.writeFileSync(path.join(devtoolsDir, 'README.md'), readme);
    }

    /**
     * Clean up generated code
     */
    private cleanGeneratedCode(code: string): string {
        // Remove markdown code blocks if present
        let cleaned = code.replace(/\`\`\`javascript\n?/g, '').replace(/\`\`\`\n?/g, '');
        
        // Remove markdown headers
        cleaned = cleaned.replace(/^#+ .*$/gm, '');
        
        return cleaned.trim();
    }

    /**
     * Check if Chrome DevTools dependencies are installed
     */
    async checkDependencies(projectPath: string): Promise<boolean> {
        const packageJsonPath = path.join(projectPath, 'package.json');
        if (!fs.existsSync(packageJsonPath)) {
            return false;
        }

        try {
            const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
            const hasPuppeteer = !!(
                packageJson.dependencies?.puppeteer ||
                packageJson.devDependencies?.puppeteer
            );
            return hasPuppeteer;
        } catch {
            return false;
        }
    }

    /**
     * Install Chrome DevTools dependencies
     */
    async installDependencies(projectPath: string): Promise<void> {
        this.outputChannel.appendLine('📦 Installing Chrome DevTools dependencies...');
        
        const terminal = vscode.window.createTerminal('TestFox - Install Chrome DevTools');
        terminal.show();
        
        terminal.sendText('npm install --save-dev puppeteer chrome-launcher jest jest-html-reporter');
    }
}
