import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { getOpenRouterService } from '../ai/openRouterService';

/**
 * Playwright Test Generator - Creates comprehensive Playwright test suites using AI
 */
export interface PlaywrightTestSuite {
    name: string;
    description: string;
    tests: PlaywrightTest[];
    config?: any;
}

export interface PlaywrightTest {
    name: string;
    description: string;
    code: string;
    fileName: string;
}

export class PlaywrightTestGenerator {
    private outputChannel: vscode.OutputChannel;

    constructor() {
        this.outputChannel = vscode.window.createOutputChannel('TestFox Playwright Generator');
    }

    /**
     * Create complete Playwright test folder structure with AI-generated tests
     */
    async generatePlaywrightSuite(projectPath: string, projectInfo: any): Promise<string> {
        this.outputChannel.appendLine('🎭 Starting Playwright test suite generation...');

        const playwrightDir = path.join(projectPath, 'tests', 'playwright');
        
        // Create directory structure
        this.createDirectoryStructure(playwrightDir);
        
        // Generate configuration
        await this.generateConfig(playwrightDir, projectInfo);
        
        // Generate fixtures
        await this.generateFixtures(playwrightDir, projectInfo);
        
        // Generate AI-powered tests
        await this.generateAITests(playwrightDir, projectInfo);
        
        // Generate utility files
        await this.generateUtilities(playwrightDir);
        
        this.outputChannel.appendLine(`✅ Playwright test suite created at: ${playwrightDir}`);
        
        return playwrightDir;
    }

    /**
     * Create directory structure
     */
    private createDirectoryStructure(baseDir: string): void {
        const dirs = [
            baseDir,
            path.join(baseDir, 'e2e'),
            path.join(baseDir, 'e2e', 'auth'),
            path.join(baseDir, 'e2e', 'navigation'),
            path.join(baseDir, 'e2e', 'forms'),
            path.join(baseDir, 'e2e', 'api'),
            path.join(baseDir, 'fixtures'),
            path.join(baseDir, 'pages'),
            path.join(baseDir, 'utils'),
            path.join(baseDir, 'screenshots'),
            path.join(baseDir, 'reports')
        ];

        for (const dir of dirs) {
            if (!fs.existsSync(dir)) {
                fs.mkdirSync(dir, { recursive: true });
                this.outputChannel.appendLine(`📁 Created: ${dir}`);
            }
        }
    }

    /**
     * Generate playwright.config.ts
     */
    private async generateConfig(playwrightDir: string, projectInfo: any): Promise<void> {
        const baseUrl = projectInfo?.baseUrl || 'http://localhost:3000';
        
        const config = `import { defineConfig, devices } from '@playwright/test';

/**
 * Playwright Test Configuration - Generated by TestFox AI
 */
export default defineConfig({
    testDir: './e2e',
    fullyParallel: true,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    workers: process.env.CI ? 1 : undefined,
    reporter: [
        ['html', { outputFolder: './reports/html-report' }],
        ['json', { outputFile: './reports/test-results.json' }],
        ['list']
    ],
    use: {
        baseURL: '${baseUrl}',
        trace: 'on-first-retry',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure',
        actionTimeout: 15000,
        navigationTimeout: 30000,
    },
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] },
        },
        {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] },
        },
        {
            name: 'webkit',
            use: { ...devices['Desktop Safari'] },
        },
        {
            name: 'Mobile Chrome',
            use: { ...devices['Pixel 5'] },
        },
        {
            name: 'Mobile Safari',
            use: { ...devices['iPhone 12'] },
        },
    ],
    webServer: {
        command: 'npm run dev',
        url: '${baseUrl}',
        reuseExistingServer: !process.env.CI,
    },
});
`;

        const configPath = path.join(playwrightDir, 'playwright.config.ts');
        fs.writeFileSync(configPath, config);
        this.outputChannel.appendLine(`📝 Generated: playwright.config.ts`);
    }

    /**
     * Generate fixtures
     */
    private async generateFixtures(playwrightDir: string, projectInfo: any): Promise<void> {
        const fixtures = `import { test as base, expect } from '@playwright/test';
import { LoginPage } from '../pages/LoginPage';
import { DashboardPage } from '../pages/DashboardPage';

/**
 * Test Fixtures - Generated by TestFox AI
 */
export type TestFixtures = {
    loginPage: LoginPage;
    dashboardPage: DashboardPage;
    authenticatedPage: any;
};

export const test = base.extend<TestFixtures>({
    loginPage: async ({ page }, use) => {
        const loginPage = new LoginPage(page);
        await use(loginPage);
    },
    
    dashboardPage: async ({ page }, use) => {
        const dashboardPage = new DashboardPage(page);
        await use(dashboardPage);
    },
    
    authenticatedPage: async ({ page, baseURL }, use) => {
        // Pre-authenticated page fixture
        await page.goto(\`\${baseURL}/login\`);
        // Add authentication logic here based on your app
        await use(page);
    },
});

export { expect };
`;

        const fixturesPath = path.join(playwrightDir, 'fixtures', 'index.ts');
        fs.writeFileSync(fixturesPath, fixtures);
        this.outputChannel.appendLine(`📝 Generated: fixtures/index.ts`);
    }

    /**
     * Generate AI-powered tests
     */
    private async generateAITests(playwrightDir: string, projectInfo: any): Promise<void> {
        const openRouter = getOpenRouterService();
        
        if (!openRouter.isConfigured()) {
            this.outputChannel.appendLine('⚠️ OpenRouter not configured, using template tests');
            await this.generateTemplateTests(playwrightDir, projectInfo);
            return;
        }

        try {
            // Generate smoke tests
            this.outputChannel.appendLine('🤖 Generating smoke tests with AI...');
            const smokeTestCode = await openRouter.generateTestCode(
                'Create smoke tests for basic application functionality: page loads, navigation works, no console errors',
                'playwright'
            );
            fs.writeFileSync(
                path.join(playwrightDir, 'e2e', 'smoke.spec.ts'),
                this.cleanGeneratedCode(smokeTestCode)
            );

            // Generate authentication tests
            this.outputChannel.appendLine('🤖 Generating authentication tests with AI...');
            const authTestCode = await openRouter.generateTestCode(
                'Create authentication tests: login flow, logout flow, protected routes, session management',
                'playwright'
            );
            fs.writeFileSync(
                path.join(playwrightDir, 'e2e', 'auth', 'authentication.spec.ts'),
                this.cleanGeneratedCode(authTestCode)
            );

            // Generate form tests based on project forms
            if (projectInfo?.forms?.length > 0) {
                this.outputChannel.appendLine('🤖 Generating form tests with AI...');
                const formTestCode = await openRouter.generateTestCode(
                    `Create form validation and submission tests for: ${projectInfo.forms.map((f: any) => f.name || f.id).join(', ')}`,
                    'playwright'
                );
                fs.writeFileSync(
                    path.join(playwrightDir, 'e2e', 'forms', 'validation.spec.ts'),
                    this.cleanGeneratedCode(formTestCode)
                );
            }

            // Generate accessibility tests
            this.outputChannel.appendLine('🤖 Generating accessibility tests with AI...');
            const a11yTestCode = await openRouter.generateTestCode(
                'Create accessibility tests using Axe: WCAG 2.1 AA compliance, keyboard navigation, screen reader compatibility',
                'playwright'
            );
            fs.writeFileSync(
                path.join(playwrightDir, 'e2e', 'accessibility.spec.ts'),
                this.cleanGeneratedCode(a11yTestCode)
            );

            // Generate API integration tests
            if (projectInfo?.endpoints?.length > 0) {
                this.outputChannel.appendLine('🤖 Generating API tests with AI...');
                const apiTestCode = await openRouter.generateTestCode(
                    `Create API integration tests for endpoints: ${projectInfo.endpoints.map((e: any) => e.path).join(', ')}`,
                    'playwright'
                );
                fs.writeFileSync(
                    path.join(playwrightDir, 'e2e', 'api', 'integration.spec.ts'),
                    this.cleanGeneratedCode(apiTestCode)
                );
            }

        } catch (error: any) {
            this.outputChannel.appendLine(`❌ AI generation failed: ${error.message}`);
            await this.generateTemplateTests(playwrightDir, projectInfo);
        }
    }

    /**
     * Generate template tests when AI is not available
     */
    private async generateTemplateTests(playwrightDir: string, projectInfo: any): Promise<void> {
        const baseUrl = projectInfo?.baseUrl || 'http://localhost:3000';

        // Smoke tests
        const smokeTests = `import { test, expect } from '@playwright/test';

/**
 * Smoke Tests - Generated by TestFox
 * Basic application health checks
 */

test.describe('Application Smoke Tests', () => {
    test('page loads successfully', async ({ page }) => {
        await page.goto('/');
        await expect(page).toHaveTitle(/.*/);
        await expect(page.locator('body')).toBeVisible();
    });

    test('no console errors on load', async ({ page }) => {
        const errors: string[] = [];
        page.on('console', msg => {
            if (msg.type() === 'error') {
                errors.push(msg.text());
            }
        });
        
        await page.goto('/');
        await page.waitForLoadState('networkidle');
        
        expect(errors).toHaveLength(0);
    });

    test('main navigation is visible', async ({ page }) => {
        await page.goto('/');
        
        // Common navigation selectors
        const navSelectors = ['nav', 'header', '[role="navigation"]'];
        let navFound = false;
        
        for (const selector of navSelectors) {
            if (await page.locator(selector).isVisible().catch(() => false)) {
                navFound = true;
                break;
            }
        }
        
        expect(navFound).toBeTruthy();
    });
});
`;
        fs.writeFileSync(path.join(playwrightDir, 'e2e', 'smoke.spec.ts'), smokeTests);

        // Authentication tests
        const authTests = `import { test, expect } from '@playwright/test';

/**
 * Authentication Tests - Generated by TestFox
 */

test.describe('Authentication Flow', () => {
    test('login page is accessible', async ({ page }) => {
        await page.goto('/login');
        await expect(page.locator('input[type="email"], input[type="text"], input[name="username"]')).toBeVisible();
        await expect(page.locator('input[type="password"], input[name="password"]')).toBeVisible();
    });

    test('login with invalid credentials shows error', async ({ page }) => {
        await page.goto('/login');
        
        await page.fill('input[type="email"], input[name="username"]', 'invalid@example.com');
        await page.fill('input[type="password"]', 'wrongpassword');
        await page.click('button[type="submit"], button:has-text("Login"), button:has-text("Sign In")');
        
        // Error message should appear
        await expect(page.locator('.error, .alert, [role="alert"], .text-error')).toBeVisible();
    });

    test('logout redirects to login', async ({ page }) => {
        // This test assumes user is authenticated
        await page.goto('/');
        
        // Try to find and click logout
        const logoutButton = page.locator('button:has-text("Logout"), a:has-text("Logout"), button:has-text("Sign Out")');
        if (await logoutButton.isVisible().catch(() => false)) {
            await logoutButton.click();
            await expect(page).toHaveURL(/.*login.*/);
        }
    });
});
`;
        fs.writeFileSync(path.join(playwrightDir, 'e2e', 'auth', 'authentication.spec.ts'), authTests);

        // Accessibility tests
        const a11yTests = `import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

/**
 * Accessibility Tests - Generated by TestFox
 */

test.describe('Accessibility Tests', () => {
    test('should not have any automatically detectable WCAG violations', async ({ page }) => {
        await page.goto('/');
        
        const accessibilityScanResults = await new AxeBuilder({ page })
            .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
            .analyze();
        
        expect(accessibilityScanResults.violations).toEqual([]);
    });

    test('keyboard navigation works for interactive elements', async ({ page }) => {
        await page.goto('/');
        
        // Tab through interactive elements
        await page.keyboard.press('Tab');
        const focusedElement = page.locator(':focus');
        
        await expect(focusedElement).toBeVisible();
    });

    test('images have alt text', async ({ page }) => {
        await page.goto('/');
        
        const images = await page.locator('img').all();
        for (const img of images) {
            const alt = await img.getAttribute('alt');
            expect(alt).not.toBeNull();
            expect(alt?.trim()).not.toBe('');
        }
    });

    test('form inputs have associated labels', async ({ page }) => {
        await page.goto('/');
        
        const inputs = await page.locator('input:not([type="hidden"]), select, textarea').all();
        for (const input of inputs) {
            const id = await input.getAttribute('id');
            const ariaLabel = await input.getAttribute('aria-label');
            const ariaLabelledBy = await input.getAttribute('aria-labelledby');
            const placeholder = await input.getAttribute('placeholder');
            
            // Should have some form of label
            const hasLabel = id && (await page.locator(\`label[for="\${id}"]\`).count() > 0) ||
                           ariaLabel || 
                           ariaLabelledBy ||
                           placeholder;
            
            expect(hasLabel).toBeTruthy();
        }
    });
});
`;
        fs.writeFileSync(path.join(playwrightDir, 'e2e', 'accessibility.spec.ts'), a11yTests);

        // Form tests
        const formTests = `import { test, expect } from '@playwright/test';

/**
 * Form Validation Tests - Generated by TestFox
 */

test.describe('Form Validation', () => {
    test('required fields show validation', async ({ page }) => {
        await page.goto('/');
        
        // Find a form
        const form = page.locator('form').first();
        if (await form.isVisible().catch(() => false)) {
            // Submit without filling
            await form.locator('button[type="submit"]').click();
            
            // Check for validation errors
            const errorVisible = await page.locator('.error, [role="alert"], .invalid-feedback').isVisible().catch(() => false);
            expect(errorVisible).toBeTruthy();
        }
    });

    test('email field validates format', async ({ page }) => {
        const emailInput = page.locator('input[type="email"]').first();
        if (await emailInput.isVisible().catch(() => false)) {
            await emailInput.fill('invalid-email');
            await emailInput.blur();
            
            // Browser should show validation
            const isValid = await emailInput.evaluate(el => (el as HTMLInputElement).validity.valid);
            expect(isValid).toBeFalsy();
        }
    });
});
`;
        fs.writeFileSync(path.join(playwrightDir, 'e2e', 'forms', 'validation.spec.ts'), formTests);
    }

    /**
     * Generate page objects
     */
    private async generateUtilities(playwrightDir: string): Promise<void> {
        // Login Page Object
        const loginPage = `import { Page, Locator, expect } from '@playwright/test';

/**
 * Login Page Object - Generated by TestFox
 */
export class LoginPage {
    readonly page: Page;
    readonly usernameInput: Locator;
    readonly passwordInput: Locator;
    readonly submitButton: Locator;
    readonly errorMessage: Locator;

    constructor(page: Page) {
        this.page = page;
        this.usernameInput = page.locator('input[type="email"], input[name="username"], input[name="email"]').first();
        this.passwordInput = page.locator('input[type="password"]').first();
        this.submitButton = page.locator('button[type="submit"], button:has-text("Login"), button:has-text("Sign In")').first();
        this.errorMessage = page.locator('.error, .alert, [role="alert"]').first();
    }

    async goto() {
        await this.page.goto('/login');
    }

    async login(username: string, password: string) {
        await this.usernameInput.fill(username);
        await this.passwordInput.fill(password);
        await this.submitButton.click();
    }

    async expectError() {
        await expect(this.errorMessage).toBeVisible();
    }
}
`;
        fs.writeFileSync(path.join(playwrightDir, 'pages', 'LoginPage.ts'), loginPage);

        // Dashboard Page Object
        const dashboardPage = `import { Page, Locator, expect } from '@playwright/test';

/**
 * Dashboard Page Object - Generated by TestFox
 */
export class DashboardPage {
    readonly page: Page;
    readonly heading: Locator;
    readonly navigation: Locator;
    readonly userMenu: Locator;

    constructor(page: Page) {
        this.page = page;
        this.heading = page.locator('h1').first();
        this.navigation = page.locator('nav').first();
        this.userMenu = page.locator('[data-testid="user-menu"], .user-menu, button:has-text("Account")').first();
    }

    async goto() {
        await this.page.goto('/dashboard');
    }

    async expectLoaded() {
        await expect(this.heading).toBeVisible();
    }
}
`;
        fs.writeFileSync(path.join(playwrightDir, 'pages', 'DashboardPage.ts'), dashboardPage);

        // Utility helpers
        const utils = `/**
 * Test Utilities - Generated by TestFox
 */

export async function waitForNetworkIdle(page: any, timeout = 5000) {
    await page.waitForLoadState('networkidle', { timeout });
}

export async function clearCookies(page: any, context: any) {
    await context.clearCookies();
}

export function generateRandomEmail() {
    const timestamp = Date.now();
    return \`test-\${timestamp}@example.com\`;
}

export function generateRandomString(length = 10) {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    let result = '';
    for (let i = 0; i < length; i++) {
        result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
}
`;
        fs.writeFileSync(path.join(playwrightDir, 'utils', 'helpers.ts'), utils);

        // README for Playwright tests
        const readme = `# Playwright Test Suite - Generated by TestFox

This comprehensive test suite was generated by TestFox AI.

## Structure

\`\`\`
tests/playwright/
├── playwright.config.ts        # Test configuration
├── fixtures/                   # Test fixtures
│   └── index.ts
├── pages/                      # Page objects
│   ├── LoginPage.ts
│   └── DashboardPage.ts
├── e2e/                        # Test files
│   ├── smoke.spec.ts          # Basic health checks
│   ├── accessibility.spec.ts  # A11y tests
│   ├── auth/                  # Authentication
│   ├── forms/                 # Form validation
│   └── api/                   # API integration
├── utils/                      # Utilities
│   └── helpers.ts
└── reports/                    # Test reports
\`\`\`

## Running Tests

\`\`\`bash
# Run all tests
npx playwright test

# Run in UI mode
npx playwright test --ui

# Run specific test file
npx playwright test smoke.spec.ts

# Run with specific browser
npx playwright test --project=chromium

# Run in headed mode
npx playwright test --headed
\`\`\`

## Adding Tests

1. Create new test files in \`e2e/\` directory
2. Use Page Objects from \`pages/\` directory
3. Use fixtures from \`fixtures/index.ts\`

## Generated by
TestFox AI - Your intelligent testing companion 🤖
`;
        fs.writeFileSync(path.join(playwrightDir, 'README.md'), readme);
    }

    /**
     * Generate MCP-optimized tests for Playwright MCP Server
     * These tests use accessibility tree selectors (roles, labels, text) 
     * instead of CSS selectors for better MCP compatibility
     */
    async generateMCPTests(playwrightDir: string, projectInfo: any): Promise<void> {
        this.outputChannel.appendLine('🎭 Generating MCP-optimized Playwright tests...');
        
        const baseUrl = projectInfo?.baseUrl || 'http://localhost:3000';

        // MCP-optimized smoke tests using accessibility tree
        const mcpSmokeTests = `import { test, expect } from '@playwright/test';

/**
 * MCP-Optimized Smoke Tests - Generated by TestFox
 * Uses accessibility tree selectors (roles, labels, text)
 * Compatible with Playwright MCP Server (@playwright/mcp)
 */

test.describe('MCP Smoke Tests', () => {
    test('page loads with accessible title', async ({ page }) => {
        await page.goto('${baseUrl}');
        
        // Use accessibility tree - check for heading role
        const heading = page.getByRole('heading', { level: 1 });
        await expect(heading).toBeVisible();
        
        // Verify page has accessible landmark regions
        await expect(page.getByRole('main')).toBeVisible();
    });

    test('navigation is accessible', async ({ page }) => {
        await page.goto('${baseUrl}');
        
        // Use accessibility roles instead of CSS selectors
        const nav = page.getByRole('navigation');
        await expect(nav).toBeVisible();
        
        // Check for links by role
        const links = page.getByRole('link');
        const count = await links.count();
        expect(count).toBeGreaterThan(0);
    });

    test('forms have accessible labels', async ({ page }) => {
        await page.goto('${baseUrl}');
        
        // Check for form elements with proper accessibility
        const buttons = page.getByRole('button');
        const buttonCount = await buttons.count();
        
        // If there are interactive elements, verify they're accessible
        if (buttonCount > 0) {
            for (let i = 0; i < Math.min(buttonCount, 5); i++) {
                const button = buttons.nth(i);
                const label = await button.getAttribute('aria-label') || 
                             await button.textContent();
                expect(label).toBeTruthy();
            }
        }
    });

    test('images have alt text', async ({ page }) => {
        await page.goto('${baseUrl}');
        
        const images = page.locator('img');
        const count = await images.count();
        
        for (let i = 0; i < count; i++) {
            const alt = await images.nth(i).getAttribute('alt');
            // Alt can be empty for decorative, but should exist
            expect(alt).not.toBeNull();
        }
    });

    test('no console errors', async ({ page }) => {
        const errors: string[] = [];
        
        page.on('console', msg => {
            if (msg.type() === 'error') {
                errors.push(msg.text());
            }
        });
        
        await page.goto('${baseUrl}');
        await page.waitForLoadState('networkidle');
        
        expect(errors).toHaveLength(0);
    });
});

test.describe('MCP Browser Actions', () => {
    test('can click buttons by accessible name', async ({ page }) => {
        await page.goto('${baseUrl}');
        
        // Try to find and click common buttons by accessible text
        const commonButtons = ['Submit', 'Save', 'Continue', 'Next', 'Login'];
        
        for (const buttonText of commonButtons) {
            const button = page.getByRole('button', { name: buttonText, exact: false });
            if (await button.isVisible().catch(() => false)) {
                await button.click();
                break;
            }
        }
    });

    test('can fill forms with labeled inputs', async ({ page }) => {
        await page.goto('${baseUrl}');
        
        const inputs = page.locator('input, textarea, select');
        const count = await inputs.count();
        
        for (let i = 0; i < Math.min(count, 3); i++) {
            const input = inputs.nth(i);
            const type = await input.getAttribute('type');
            
            if (type === 'hidden' || type === 'submit') continue;
            
            if (type === 'email') {
                await input.fill('test@example.com');
            } else if (type === 'password') {
                await input.fill('TestPassword123!');
            } else {
                await input.fill('Test input data');
            }
        }
    });

    test('keyboard navigation works', async ({ page }) => {
        await page.goto('${baseUrl}');
        
        await page.keyboard.press('Tab');
        
        const focused = page.locator(':focus');
        await expect(focused).toBeVisible();
        
        await page.keyboard.press('Escape');
    });
});
`;
        fs.writeFileSync(path.join(playwrightDir, 'e2e', 'mcp-smoke.spec.ts'), mcpSmokeTests);
        this.outputChannel.appendLine('📝 Generated: e2e/mcp-smoke.spec.ts (MCP-optimized)');

        // MCP README
        const mcpReadme = `# MCP-Optimized Playwright Tests

These tests are optimized for the official Microsoft Playwright MCP Server.

## Key Features

- **Accessibility Tree Selectors**: Uses roles, labels, and text
- **MCP Compatible**: Works with Playwright MCP's tool-based automation
- **Fast & Lightweight**: No screenshots needed

## Running Tests

\`\`\`bash
npx playwright test mcp-smoke.spec.ts
\`\`\`

## MCP Server Configuration

\`\`\`json
{
  "mcpServers": {
    "playwright": {
      "command": "npx",
      "args": [
        "@playwright/mcp@latest",
        "--headless",
        "--browser=chromium",
        "--viewport-size=1280x720"
      ]
    }
  }
}
\`\`\`

## Generated by
TestFox AI 🤖
`;
        fs.writeFileSync(path.join(playwrightDir, 'MCP-README.md'), mcpReadme);
        this.outputChannel.appendLine('📝 Generated: MCP-README.md');
    }

    /**
     * Clean up generated code
     */
    private cleanGeneratedCode(code: string): string {
        // Remove markdown code blocks if present
        let cleaned = code.replace(/\`\`\`typescript\n?/g, '').replace(/\`\`\`\n?/g, '');
        
        // Remove markdown headers
        cleaned = cleaned.replace(/^#+ .*$/gm, '');
        
        return cleaned.trim();
    }

    /**
     * Check if Playwright is installed
     */
    async checkPlaywrightInstallation(projectPath: string): Promise<boolean> {
        const packageJsonPath = path.join(projectPath, 'package.json');
        if (!fs.existsSync(packageJsonPath)) {
            return false;
        }

        try {
            const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
            const hasPlaywright = !!(
                packageJson.dependencies?.playwright ||
                packageJson.devDependencies?.playwright ||
                packageJson.dependencies?.['@playwright/test'] ||
                packageJson.devDependencies?.['@playwright/test']
            );
            return hasPlaywright;
        } catch {
            return false;
        }
    }

    /**
     * Install Playwright if not present
     */
    async installPlaywright(projectPath: string): Promise<void> {
        this.outputChannel.appendLine('📦 Installing Playwright...');
        
        const terminal = vscode.window.createTerminal('TestFox - Install Playwright');
        terminal.show();
        
        terminal.sendText('npm install --save-dev @playwright/test');
        terminal.sendText('npx playwright install chromium firefox webkit');
        terminal.sendText('npm install --save-dev @axe-core/playwright');
    }
}
